-- AUTO-GENERATED seed data for assistance_centers
-- Updated with real data for Cantabria region

INSERT INTO assistance_centers (name, entity_type, support_type, region, province, city, country, coverage, website, source_url, source_type, notes, last_verified_at, latitude, longitude, geocode_status, geocode_precision, geocode_source) VALUES
('Fundación ONCE del Perro Guía (FOPG)', 'foundation', 'guide', 'Comunidad de Madrid', 'Madrid', 'Boadilla del Monte', 'Spain', 'national', 'https://perrosguia.once.es/', 'https://perrosguia.once.es/', 'official_site', 'Fundación de referencia nacional para perros guía. Camino de Alcorcón, s/n 28660 - Boadilla del Monte (Madrid). Teléfono: 916 32 46 30', '2026-02-09', '40.406', '-3.8777', 'verified', 'city', 'manual_city'),
('AEPA Euskadi (Asociación de Perros de Asistencia)', 'association', 'assistance', 'País Vasco', 'Bizkaia', 'Bilbao', 'Spain', 'regional', 'https://www.euskadi.eus/gobierno-vasco/-/asociacion/asociacion-de-perros-de-asistencia-aepa-euskadi/', 'https://www.euskadi.eus/gobierno-vasco/-/asociacion/asociacion-de-perros-de-asistencia-aepa-euskadi/', 'official_registry', 'Asociación de Perros de Asistencia AEPA Euskadi. Plaza Celestino María del Arenal, 14-10º D, 48015 Bilbao, Bizkaia. Teléfono: 944483186', '2026-02-09', '43.2525', '-2.9341', 'verified', 'city', 'manual_city'),
('AAS DISCAN', 'association', 'assistance', 'Cataluña', 'Barcelona', 'Barcelona', 'Spain', 'regional', 'https://www.discan.dog/', 'https://www.discan.dog/', 'official_site', 'AAS DISCAN (Associació d''Acció Social DISCAN). Entidad sin ánimo de lucro fundada en 2007. Teléfono: +34 692 060 858, correo electrónico: INFO@DISCAN.ORG', '2026-02-09', '41.390205', '2.154007', 'verified', 'city', 'manual_city'),
('Asociación Perros Pastores de Cantabria', 'association', 'assistance', 'Cantabria', 'Cantabria', 'Santander', 'Spain', 'regional', 'https://meetingpoint.santander.es/usuarios/perros-pastores-de-cantabria', 'https://meetingpoint.santander.es/usuarios/perros-pastores-de-cantabria', 'official_registry', 'Asociación Perros Pastores de Cantabria (APEPA). Persona de contacto: Fernando Gómez. Teléfono: 663 607 929', '2026-02-09', '43.4623', '-3.8039', 'verified', 'city', 'manual_city'),
('Servicio de terapia asistida con perros (CAD Santander y Sierrallana)', 'public_service', 'therapy', 'Cantabria', 'Cantabria', 'Santander / Torrelavega', 'Spain', 'regional', 'https://www.cantabria.es/web/comunicados/w/el-servicio-de-terapia-asistida-con-perros-en-los-cad-de-santander-y-sierrallana-funciona-a-pleno-rendimiento', 'https://www.cantabria.es/web/comunicados/w/el-servicio-de-terapia-asistida-con-perros-en-los-cad-de-santander-y-sierrallana-funciona-a-pleno-rendimiento', 'official_municipal', 'Servicio público en centros CAD con terapia asistida con perros.', '2026-02-09', '43.46', '-3.8', 'verified', 'city', 'manual_city'),
('Residencia La Pereda (Programa de terapia asistida con perros)', 'program', 'therapy', 'Cantabria', 'Cantabria', 'Santander', 'Spain', 'local', 'https://www.residencialapereda.com/programas/programa-de-terapia-asistida-con-perros/', 'https://www.residencialapereda.com/programas/programa-de-terapia-asistida-con-perros/', 'official_site', 'Programa de terapia asistida con perros en residencia.', '2026-02-09', '43.46', '-3.8', 'verified', 'city', 'manual_city'),
('Centro de Terapias Asistidas con Canes (CTAC)', 'center', 'therapy', 'Cataluña', 'Barcelona', 'Barcelona', 'Spain', 'regional', 'https://ctac.cat/', 'https://ctac.cat/', 'official_site', 'Centro de Terapias Asistadas con Canes (CTAC) en Barcelona. Organización privada especializada en terapias asistidas con animales y formación en IAA.', '2026-02-09', '41.390205', '2.154007', 'verified', 'city', 'manual_city'),
('Asociación Española de Perros de Apoyo', 'association', 'assistance', 'Madrid', 'Madrid', 'Madrid', 'Spain', 'national', 'https://perrosdeapoyo.es/asociacion/', 'https://perrosdeapoyo.es/asociacion/', 'official_site', 'Asociación Española de Perros de Apoyo. Nace con el objetivo de hacer que los perros sean un apoyo en la vida cotidiana de las personas.', '2026-02-09', '40.4168', '-3.7038', 'verified', 'city', 'manual_city'),
('Grupo del Perro de Salvamento de Euskadi (GPS-LTT Euskadi)', 'association', 'assistance', 'País Vasco', 'Gipuzkoa', 'Donostia', 'Spain', 'regional', 'http://www.gpseuskadi.org/', 'http://www.gpseuskadi.org/', 'official_site', 'Tenemos como objetivo principal preparar equipos formados por un Guía y un Perro, destinados a la localización de personas perdidas en el monte, sepultadas en avalanchas o en la mar.', '2026-02-09', '43.3183', '-1.9812', 'verified', 'city', 'manual_city'),
('Áskal Red Internacional de Profesionales de la Educación Canina', 'organization', 'assistance', 'País Vasco', 'Gipuzkoa', 'Donostia', 'Spain', 'international', 'https://www.askal.es/', 'https://www.askal.es/', 'official_site', 'Áskal es una red internacional de profesionales de la educación canina especializados en perros de asistencia, con presencia en España y América Latina.', '2026-02-09', '43.3183', '-1.9812', 'verified', 'city', 'manual_city');
