-- Seed data for bookings table
INSERT INTO bookings (service_id, user_id, dog_id, start_at, end_at, status) VALUES
((SELECT s.id FROM services s JOIN providers p ON s.provider_id = p.id WHERE p.name = 'Clínica Veterinaria San Carlos' AND s.name = 'Consulta veterinaria general'), (SELECT id FROM users WHERE email = 'maria.gonzalez@example.com'), (SELECT id FROM dogs WHERE name = 'Max'), '2026-02-15 10:00:00', '2026-02-15 10:30:00', 'confirmed'),
((SELECT s.id FROM services s JOIN providers p ON s.provider_id = p.id WHERE p.name = 'Guardería Canina El Refugio' AND s.name = 'Alojamiento diario'), (SELECT id FROM users WHERE email = 'carlos.ruiz@example.com'), (SELECT id FROM dogs WHERE name = 'Luna'), '2026-02-20 08:00:00', '2026-02-22 18:00:00', 'confirmed'),
((SELECT s.id FROM services s JOIN providers p ON s.provider_id = p.id WHERE p.name = 'Tienda Mascotas Happy Pets' AND s.name = 'Compra de alimento premium'), (SELECT id FROM users WHERE email = 'ana.sanchez@example.com'), (SELECT id FROM dogs WHERE name = 'Rocky'), '2026-02-12 12:00:00', '2026-02-12 12:10:00', 'completed'),
((SELECT s.id FROM services s JOIN providers p ON s.provider_id = p.id WHERE p.name = 'Pelucas y Paseos' AND s.name = 'Peluquería canina completa'), (SELECT id FROM users WHERE email = 'pablo.diaz@example.com'), (SELECT id FROM dogs WHERE name = 'Bella'), '2026-02-18 09:00:00', '2026-02-18 10:30:00', 'pending'),
((SELECT s.id FROM services s JOIN providers p ON s.provider_id = p.id WHERE p.name = 'Entrenador Canino Profesional' AND s.name = 'Sesión de entrenamiento básico'), (SELECT id FROM users WHERE email = 'lucia.martinez@example.com'), (SELECT id FROM dogs WHERE name = 'Charlie'), '2026-02-14 16:00:00', '2026-02-14 17:00:00', 'confirmed'),
((SELECT s.id FROM services s JOIN providers p ON s.provider_id = p.id WHERE p.name = 'Telemedicina VetOnline' AND s.name = 'Consulta online urgente'), (SELECT id FROM users WHERE email = 'javier.hernandez@example.com'), (SELECT id FROM dogs WHERE name = 'Daisy'), '2026-02-10 11:30:00', '2026-02-10 12:00:00', 'completed'),
((SELECT s.id FROM services s JOIN providers p ON s.provider_id = p.id WHERE p.name = 'Transporte PetFriendly' AND s.name = 'Transporte local (hasta 50km)'), (SELECT id FROM users WHERE email = 'carmen.lopez@example.com'), (SELECT id FROM dogs WHERE name = 'Cooper'), '2026-02-25 14:00:00', '2026-02-25 15:00:00', 'pending'),
((SELECT s.id FROM services s JOIN providers p ON s.provider_id = p.id WHERE p.name = 'Rutas Caninas Aventura' AND s.name = 'Ruta senderismo familiar'), (SELECT id FROM users WHERE email = 'david.moreno@example.com'), (SELECT id FROM dogs WHERE name = 'Zoe'), '2026-03-05 09:00:00', '2026-03-05 14:00:00', 'confirmed'),
((SELECT s.id FROM services s JOIN providers p ON s.provider_id = p.id WHERE p.name = 'Seguros Mascota Segura' AND s.name = 'Póliza básica'), (SELECT id FROM users WHERE email = 'patricia.alvarez@example.com'), (SELECT id FROM dogs WHERE name = 'Toby'), '2026-02-16 15:00:00', '2026-02-16 15:15:00', 'completed'),
((SELECT s.id FROM services s JOIN providers p ON s.provider_id = p.id WHERE p.name = 'Centro de Terapia Asistida con Animales' AND s.name = 'Sesión de terapia asistida'), (SELECT id FROM users WHERE email = 'raul.torres@example.com'), (SELECT id FROM dogs WHERE name = 'Molly'), '2026-02-19 17:00:00', '2026-02-19 18:00:00', 'confirmed');