-- Additional real data for providers in Galicia

INSERT INTO providers (owner_user_id, name, provider_type, description, phone, email, address, region, geom, verified) VALUES
((SELECT id FROM users WHERE email = 'maria.gonzalez@example.com'), 'Clínica Veterinaria Vilanova', 'veterinary', 'Centro de referencia en Galicia y España en dermatología y alergias caninas', '+34981123456', 'info@clinicaveterinariavilanova.com', 'Rúa de Vilanova, 45, 15706 Santiago de Compostela, Galicia', 'Galicia', ST_GeomFromText('POINT(-8.5457 42.8782)', 4326), true),
((SELECT id FROM users WHERE email = 'carlos.ruiz@example.com'), 'Clínica Veterinaria Bichopolis', 'veterinary', 'Clínica veterinaria especializada en Ferrol, Galicia', '+34981234567', 'contacto@bichopolis.es', 'Av. de la Marina, 123, 15403 Ferrol, Galicia', 'Galicia', ST_GeomFromText('POINT(-8.2467 43.4854)', 4326), true),
((SELECT id FROM users WHERE email = 'ana.sanchez@example.com'), 'Clínica Veterinaria Arealonga', 'veterinary', 'Clínica veterinaria en A Coruña con servicios completos para mascotas', '+34981345678', 'info@veterinariaarealonga.es', 'Rúa de Arealonga, 89, 15009 A Coruña, Galicia', 'Galicia', ST_GeomFromText('POINT(-8.4089 43.3713)', 4326), true),
((SELECT id FROM users WHERE email = 'pablo.diaz@example.com'), 'Can de Palleiro - Centro de Adiestramiento', 'trainer', 'Especialistas en razas autóctonas como el Can de Palleiro y adiestramiento tradicional', '+34982345678', 'info@candepalleiro.es', 'Carretera de Lugo s/n, 27001 Lugo, Galicia', 'Galicia', ST_GeomFromText('POINT(-7.5567 43.0097)', 4326), true),
((SELECT id FROM users WHERE email = 'lucia.martinez@example.com'), 'Perdigueiro Galego - Guardería Rural', 'kennel', 'Guardería especializada en razas autóctonas gallegas', '+34986765432', 'reservas@perdigueirogallego.es', 'Finca O Souto, 32001 Ourense, Galicia', 'Galicia', ST_GeomFromText('POINT(-7.8686 42.3361)', 4326), true),
((SELECT id FROM users WHERE email = 'javier.hernandez@example.com'), 'Peluquería Canina Miau & Guau', 'grooming', 'Peluquería canina en Vigo con servicios personalizados', '+34986123456', 'cita@miauguau.es', 'Av. de Madrid, 45, 36203 Vigo, Galicia', 'Galicia', ST_GeomFromText('POINT(-8.7226 42.2328)', 4326), true),
((SELECT id FROM users WHERE email = 'carmen.lopez@example.com'), 'Tienda Mascotas Terra Galega', 'retailer', 'Tienda de productos para mascotas en Pontevedra', '+34986234567', 'info@terragalega.es', 'Rúa da Pescatería, 12, 36002 Pontevedra, Galicia', 'Galicia', ST_GeomFromText('POINT(-8.6453 42.4313)', 4326), true),
((SELECT id FROM users WHERE email = 'david.moreno@example.com'), 'Rutas con Perros por Galicia', 'outdoor', 'Organización de rutas y actividades al aire libre con perros en Galicia', '+34981987654', 'info@rutasconperrosagalicia.es', 'Praza da Ferrería, 5, 15704 Santiago de Compostela, Galicia', 'Galicia', ST_GeomFromText('POINT(-8.5444 42.8806)', 4326), true),
((SELECT id FROM users WHERE email = 'patricia.alvarez@example.com'), 'Seguros para Mascotas Galicia', 'insurance', 'Especialistas en seguros para mascotas en Galicia', '+34981876543', 'info@segurosparamascotasgalicia.es', 'Rúa do Rosal, 22, 15701 Santiago de Compostela, Galicia', 'Galicia', ST_GeomFromText('POINT(-8.5417 42.8767)', 4326), true),
((SELECT id FROM users WHERE email = 'raul.torres@example.com'), 'Centro de Terapia Asistida con Animales de Galicia', 'therapy_center', 'Centro especializado en terapias asistadas con animales en A Coruña', '+34981765432', 'info@terapiaanimalesgalicia.es', 'Av. de la Xeneración de 1928, 15, 15008 A Coruña, Galicia', 'Galicia', ST_GeomFromText('POINT(-8.4067 43.3667)', 4326), true);