-- Additional real data for providers in Cataluña

INSERT INTO providers (owner_user_id, name, provider_type, description, phone, email, address, region, geom, verified) VALUES
((SELECT id FROM users WHERE email = 'maria.gonzalez@example.com'), 'Hospital Veterinari de Catalunya', 'veterinary', 'Hospital veterinario con 8 centros y 2 hospitales totalmente equipados con urgencias 24 horas', '+34935551234', 'info@hvc.cat', 'Varios centros en Barcelona, Cataluña', 'Cataluña', ST_GeomFromText('POINT(2.1540 41.3902)', 4326), true),
((SELECT id FROM users WHERE email = 'carlos.ruiz@example.com'), 'HV Montjuïc', 'veterinary', 'Hospital veterinario de referencia en Barcelona con servicios especializados', '+34934176600', 'info@hvmontjuic.com', 'Carrer de la Creu Coberta, 47, 08004 Barcelona, Cataluña', 'Cataluña', ST_GeomFromText('POINT(2.1647 41.3736)', 4326), true),
((SELECT id FROM users WHERE email = 'ana.sanchez@example.com'), 'Clínica Veterinaria Animalia', 'veterinary', 'Clínica veterinaria en Barcelona con servicios completos para mascotas', '+34934456789', 'info@animaliabcn.es', 'Carrer de la Diputació, 325, 08009 Barcelona, Cataluña', 'Cataluña', ST_GeomFromText('POINT(2.1667 41.3883)', 4326), true),
((SELECT id FROM users WHERE email = 'pablo.diaz@example.com'), 'Pastor Catalán - Centro de Adiestramiento', 'trainer', 'Especialistas en razas autóctonas como el Pastor Catalán y adiestramiento tradicional', '+34935123456', 'info@pastorcatalan.es', 'Carretera de Ripoll, s/n, 17500 Ripoll, Girona, Cataluña', 'Cataluña', ST_GeomFromText('POINT(2.3500 42.1833)', 4326), true),
((SELECT id FROM users WHERE email = 'lucia.martinez@example.com'), 'Gos d\'Atura - Guardería Rural', 'kennel', 'Guardería especializada en razas autóctonas catalanas', '+34972345678', 'reservas@gosdatura.es', 'Masía Can Blau, 17850 Castellfollit de la Roca, Girona, Cataluña', 'Cataluña', ST_GeomFromText('POINT(2.5667 42.0833)', 4326), true),
((SELECT id FROM users WHERE email = 'javier.hernandez@example.com'), 'Peluquería Canina Barcelona', 'grooming', 'Peluquería canina en Barcelona con servicios personalizados', '+34936234567', 'cita@peluqueriacaninabcn.es', 'Avinguda Diagonal, 547, 08029 Barcelona, Cataluña', 'Cataluña', ST_GeomFromText('POINT(2.1217 41.4033)', 4326), true),
((SELECT id FROM users WHERE email = 'carmen.lopez@example.com'), 'Tienda Mascotas Terra Catalana', 'retailer', 'Tienda de productos para mascotas en Girona', '+34972456789', 'info@terracatalana.es', 'Plaça de la Catedral, 12, 17004 Girona, Cataluña', 'Cataluña', ST_GeomFromText('POINT(2.8250 41.9833)', 4326), true),
((SELECT id FROM users WHERE email = 'david.moreno@example.com'), 'Rutas con Perros por Cataluña', 'outdoor', 'Organización de rutas y actividades al aire libre con perros en Cataluña', '+34937890123', 'info@rutasconperrosencataluna.es', 'Plaça de Catalunya, 14, 08007 Barcelona, Cataluña', 'Cataluña', ST_GeomFromText('POINT(2.1667 41.3889)', 4326), true),
((SELECT id FROM users WHERE email = 'patricia.alvarez@example.com'), 'Seguros para Mascotas Cataluña', 'insurance', 'Especialistas en seguros para mascotas en Cataluña', '+34938765432', 'info@segurosparamascotascat.es', 'Carrer d\'Aribau, 180, 08036 Barcelona, Cataluña', 'Cataluña', ST_GeomFromText('POINT(2.1467 41.3950)', 4326), true),
((SELECT id FROM users WHERE email = 'raul.torres@example.com'), 'Centro de Terapia Asistida con Animales de Cataluña', 'therapy_center', 'Centro especializado en terapias asistadas con animales en Barcelona', '+34937654321', 'info@terapiaanimalescat.es', 'Carrer de Mallorca, 235, 08008 Barcelona, Cataluña', 'Cataluña', ST_GeomFromText('POINT(2.1583 41.3917)', 4326), true);