-- Additional real data for providers in Aragón

INSERT INTO providers (owner_user_id, name, provider_type, description, phone, email, address, region, geom, verified) VALUES
((SELECT id FROM users WHERE email = 'maria.gonzalez@example.com'), 'Veteriona Clínica Veterinaria', 'veterinary', 'Clínica veterinaria en Zaragoza con servicios completos para mascotas', '+34976265845', 'info@veteriona.es', 'Calle Coso 123, 50001 Zaragoza, Aragón', 'Aragón', ST_GeomFromText('POINT(-0.8773 41.6561)', 4326), true),
((SELECT id FROM users WHERE email = 'carlos.ruiz@example.com'), 'Clínica Veterinaria Artemisa', 'veterinary', 'Clínica veterinaria especializada en pequeños animales en Zaragoza', '+34976294856', 'info@veterinariaartemisa.es', 'Avenida de Navarra 45, 50006 Zaragoza, Aragón', 'Aragón', ST_GeomFromText('POINT(-0.8850 41.6450)', 4326), true),
((SELECT id FROM users WHERE email = 'ana.sanchez@example.com'), 'Argos Clínica Veterinaria', 'veterinary', 'Centro veterinario con servicios de urgencia 24 horas en Zaragoza', '+34976567890', 'urgencias@argosveterinaria.es', 'Calle Ramón y Cajal 28, 50001 Zaragoza, Aragón', 'Aragón', ST_GeomFromText('POINT(-0.8790 41.6520)', 4326), true),
((SELECT id FROM users WHERE email = 'pablo.diaz@example.com'), 'Can de Chira - Centro de Adiestramiento', 'trainer', 'Especialistas en razas autóctonas como el Can de Chira y adiestramiento tradicional', '+34974567891', 'info@candechara.es', 'Carretera de Bielsa s/n, 22800 Barbastro, Huesca, Aragón', 'Aragón', ST_GeomFromText('POINT(0.1167 42.0200)', 4326), true),
((SELECT id FROM users WHERE email = 'lucia.martinez@example.com'), 'Mastín del Pirineo - Guardería Rural', 'kennel', 'Guardería especializada en razas autóctonas del Pirineo aragonés', '+34974123456', 'reservas@mastindelpirineo.es', 'Finca La Estación, 22620 Boltaña, Huesca, Aragón', 'Aragón', ST_GeomFromText('POINT(0.3667 42.4167)', 4326), true),
((SELECT id FROM users WHERE email = 'javier.hernandez@example.com'), 'Peluquería Canina Luna', 'grooming', 'Peluquería canina en Zaragoza con servicios personalizados', '+34976987654', 'cita@peluqueriacaninaluna.es', 'Calle Alfonso I 15, 50002 Zaragoza, Aragón', 'Aragón', ST_GeomFromText('POINT(-0.8750 41.6500)', 4326), true),
((SELECT id FROM users WHERE email = 'carmen.lopez@example.com'), 'Tienda Mascotas Pirineos', 'retailer', 'Tienda de productos para mascotas en Huesca', '+34974567892', 'info@tiendamascotaspireneos.es', 'Avenida de los Pirineos 33, 22002 Huesca, Aragón', 'Aragón', ST_GeomFromText('POINT(-0.4089 42.1361)', 4326), true),
((SELECT id FROM users WHERE email = 'david.moreno@example.com'), 'Rutas con Perros en los Pirineos', 'outdoor', 'Organización de rutas y actividades al aire libre con perros en los Pirineos aragoneses', '+34974987653', 'info@rutasconperrosaragon.es', 'Calle San Blas 8, 22001 Huesca, Aragón', 'Aragón', ST_GeomFromText('POINT(-0.4050 42.1350)', 4326), true),
((SELECT id FROM users WHERE email = 'patricia.alvarez@example.com'), 'Seguros para Mascotas Aragón', 'insurance', 'Especialistas en seguros para mascotas en Aragón', '+34976123456', 'info@segurosparamascotasaragon.es', 'Calle Torre Nueva 10, 50001 Zaragoza, Aragón', 'Aragón', ST_GeomFromText('POINT(-0.8760 41.6550)', 4326), true),
((SELECT id FROM users WHERE email = 'raul.torres@example.com'), 'Centro de Terapia Asistida con Animales del Ebro', 'therapy_center', 'Centro especializado en terapias asistidas con animales en Zaragoza', '+34976543210', 'info@terapiaanimalebro.es', 'Calle María Zambrano 25, 50018 Zaragoza, Aragón', 'Aragón', ST_GeomFromText('POINT(-0.8900 41.6600)', 4326), true);