-- Seed data for providers table
INSERT INTO providers (owner_user_id, name, provider_type, description, phone, email, address, region, geom, verified) VALUES
((SELECT id FROM users WHERE email = 'maria.gonzalez@example.com'), 'Hospital Veterinario Cantabria', 'veterinary', 'Hospital veterinario con servicios 24 horas, especialidades y urgencias', '+34942558862', 'info@hospitalveterinariocantabria.es', 'Polígono Industrial Guarnizo Nave 15, 39611 Guarnizo, Cantabria', 'Cantabria', ST_GeomFromText('POINT(-3.8200 43.4500)', 4326), true),
((SELECT id FROM users WHERE email = 'carlos.ruiz@example.com'), 'Cecapa – Centro Canino Parayas', 'kennel', 'Centro canino con residencia, clínica veterinaria, adiestramiento y tienda', '+34942082534', 'info@cecapa.com', 'Carretera de Herrera s/n, 39011 Santander, Cantabria', 'Cantabria', ST_GeomFromText('POINT(-3.8100 43.4600)', 4326), true),
((SELECT id FROM users WHERE email = 'ana.sanchez@example.com'), 'Tienda Cecapa', 'retailer', 'Productos para mascotas del centro canino Cecapa', '+34942254575', 'info@cecapa.com', 'Carretera de Herrera s/n, 39011 Santander, Cantabria', 'Cantabria', ST_GeomFromText('POINT(-3.8100 43.4600)', 4326), true),
((SELECT id FROM users WHERE email = 'pablo.diaz@example.com'), 'Peluquería Canina Pupetes', 'grooming', 'Servicios de peluquería canina en Maliaño, Cantabria', '+34942141346', 'info@pupetes.club', 'Cantabria, Maliaño', 'Cantabria', ST_GeomFromText('POINT(-3.8200 43.4200)', 4326), true),
((SELECT id FROM users WHERE email = 'lucia.martinez@example.com'), 'Anny and Dogs', 'trainer', 'Educación y adiestramiento canino en Cantabria', '+34615137547', 'info@annyanddogs.com', 'Calle Blas Cabrera, 7, 39005 Santander, Cantabria', 'Cantabria', ST_GeomFromText('POINT(-3.8000 43.4700)', 4326), true),
((SELECT id FROM users WHERE email = 'javier.hernandez@example.com'), 'Telemedicina VetOnline', 'telemedicine', 'Consulta veterinaria online y seguimiento de salud para perros', '+34911234567', 'consulta@vetonline.es', 'Calle Princesa, 50, Madrid', 'Comunidad de Madrid', ST_GeomFromText('POINT(-3.7038 40.4168)', 4326), true),
((SELECT id FROM users WHERE email = 'carmen.lopez@example.com'), 'Servicios Caninos', 'transport', 'Servicios especializados para perros en Cantabria', '+34634769056', 'info@servicioscaninos.es', 'Calle Cueto s/n, Santander, Cantabria', 'Cantabria', ST_GeomFromText('POINT(-3.8000 43.4600)', 4326), true),
((SELECT id FROM users WHERE email = 'david.moreno@example.com'), 'Rutas Caninas Aventura', 'outdoor', 'Organización de rutas y actividades al aire libre para perros y dueños', '+34942890123', 'rutas@rutascaninas.es', 'Monte Vielha, Reinosa', 'Cantabria', ST_GeomFromText('POINT(-4.3500 43.1000)', 4326), true),
((SELECT id FROM users WHERE email = 'patricia.alvarez@example.com'), 'Henko Seguros', 'insurance', 'Comprometidos con tu tranquilidad, seguros para mascotas en Santander', '+34942000000', 'info@seguroshenko.es', 'Santander, Cantabria', 'Cantabria', ST_GeomFromText('POINT(-3.8000 43.4600)', 4326), true),
((SELECT id FROM users WHERE email = 'raul.torres@example.com'), 'Centro de Terapia Asistida con Animales', 'therapy_center', 'Centro especializado en terapias asistidas con animales para diferentes colectivos', '+34942901234', 'info@terapiaanimal.es', 'Av. de Castilla, 10, Santander', 'Cantabria', ST_GeomFromText('POINT(-3.8000 43.4600)', 4326), true);