-- Additional real data for providers in Cantabria

INSERT INTO providers (owner_user_id, name, provider_type, description, phone, email, address, region, geom, verified) VALUES
((SELECT id FROM users WHERE email = 'maria.gonzalez@example.com'), 'Clínica Veterinaria La Salvé', 'veterinary', 'Clínica veterinaria en Laredo, Cantabria', '+34942607110', 'veterinarios@veterinarioslasalve.es', 'C. El Pelegrín, 35, Laredo (39770), Cantabria', 'Cantabria', ST_GeomFromText('POINT(-3.4083 43.4250)', 4326), true),
((SELECT id FROM users WHERE email = 'carlos.ruiz@example.com'), 'Clinica Veterinaria Parque Morales', 'veterinary', 'Clínica veterinaria en Santander, Cantabria', '+34942343788', 'veterinariaparquemorales@gmail.com', 'C. Joaquín Bustamante, 10, LOCAL 9 (CAZOÑA, 39011 Santander, Cantabria)', 'Cantabria', ST_GeomFromText('POINT(-3.8100 43.4610)', 4326), true),
((SELECT id FROM users WHERE email = 'ana.sanchez@example.com'), 'Tienda Kiwoko Torrelavega', 'retailer', 'Tienda de productos para mascotas en Torrelavega', '+34942323785', 'info.torrelavega@kiwoko.com', 'C.C.El Alisal 39011 Santander. Av. de los Remedios, 30, 39300 Torrelavega, Cantabria', 'Cantabria', ST_GeomFromText('POINT(-4.0500 43.3600)', 4326), true),
((SELECT id FROM users WHERE email = 'pablo.diaz@example.com'), 'Peluquería Canina Bagheera', 'grooming', 'Peluquería canina en Santander', '+34942401994', 'info@bagheera.es', 'C/ San Fernando 86, Santander - Cantabria', 'Cantabria', ST_GeomFromText('POINT(-3.8000 43.4650)', 4326), true),
((SELECT id FROM users WHERE email = 'lucia.martinez@example.com'), 'Bybaop Educación Canina', 'trainer', 'Educación canina en Cantabria con servicios en local y a domicilio', '+34670974124', 'info@bybaop.es', 'Santander, Cantabria', 'Cantabria', ST_GeomFromText('POINT(-3.8000 43.4600)', 4326), true),
((SELECT id FROM users WHERE email = 'carmen.lopez@example.com'), 'Peluquería Canina Tu Estilo', 'grooming', 'Peluquería canina en Santander', '+34689991229', 'tu_estilo_pelucanina@email.com', 'Calle Valliciergo, 9, 39003 Santander, Cantabria', 'Cantabria', ST_GeomFromText('POINT(-3.7950 43.4700)', 4326), true),
((SELECT id FROM users WHERE email = 'david.moreno@example.com'), 'Peluquería Canina Animalia', 'grooming', 'Peluquería canina en Santander con servicio de citas', '+34686163799', 'animalia.santander@email.com', 'Calle Floranes 40, Santander, Cantabria', 'Cantabria', ST_GeomFromText('POINT(-3.8050 43.4620)', 4326), true),
((SELECT id FROM users WHERE email = 'raul.torres@example.com'), 'Servicios Caninos Cantabria', 'trainer', 'Adiestramiento canino en Cantabria', '+34634769056', 'info@servicioscaninos.es', 'C/ Cueto s/n, Santander - Cantabria', 'Cantabria', ST_GeomFromText('POINT(-3.8000 43.4600)', 4326), true);