-- Additional real data for providers in Navarra

INSERT INTO providers (owner_user_id, name, provider_type, description, phone, email, address, region, geom, verified) VALUES
((SELECT id FROM users WHERE email = 'maria.gonzalez@example.com'), 'Clínica Veterinaria Sarriguren', 'veterinary', 'Clínica veterinaria en Egüés, Navarra', '+34948165447', 'info@veterinarios-sarriguren.com', 'Calle Bardenas Reales 6, 31621 Egüés, Navarra', 'Navarra', ST_GeomFromText('POINT(-1.6833 42.7833)', 4326), true),
((SELECT id FROM users WHERE email = 'carlos.ruiz@example.com'), 'Clinica Mi Amigo', 'veterinary', 'Clínica veterinaria en Pamplona, Navarra', '+34948234567', 'contacto@clinicami amigo.es', 'Calle Sancho el Sabio 12, 31001 Pamplona, Navarra', 'Navarra', ST_GeomFromText('POINT(-1.6433 42.8167)', 4326), true),
((SELECT id FROM users WHERE email = 'ana.sanchez@example.com'), 'Centro Clínico Veterinario Barañain', 'veterinary', 'Centro veterinario en Barañain, Navarra', '+34948234589', 'info@veterinariobaranain.es', 'Avenida Pamplona, 17, 31012 Barañain, Navarra', 'Navarra', ST_GeomFromText('POINT(-1.6667 42.8000)', 4326), true),
((SELECT id FROM users WHERE email = 'pablo.diaz@example.com'), 'Pachón Navarro - Centro de Adiestramiento', 'trainer', 'Especialistas en razas autóctonas como el Pachón Navarro y adiestramiento de caza', '+34948345678', 'info@pachonnavarroentrena.es', 'Carretera de Tudela, s/n, 31590 Cintruénigo, Navarra', 'Navarra', ST_GeomFromText('POINT(-1.7000 42.4500)', 4326), true),
((SELECT id FROM users WHERE email = 'lucia.martinez@example.com'), 'Pastor Vasco - Guardería Rural', 'kennel', 'Guardería especializada en razas autóctonas vascas y navarras', '+34948456789', 'reservas@pastorvascokennel.es', 'Finca Aralar, 31869 Baztan, Navarra', 'Navarra', ST_GeomFromText('POINT(-1.5833 43.0833)', 4326), true),
((SELECT id FROM users WHERE email = 'javier.hernandez@example.com'), 'Peluquería Canina La Curruca', 'grooming', 'Peluquería canina en Tudela con servicios personalizados', '+34948567890', 'cita@peluqueriacaninacurruca.es', 'Avenida de la Estación, 25, 31500 Tudela, Navarra', 'Navarra', ST_GeomFromText('POINT(-1.6167 42.5333)', 4326), true),
((SELECT id FROM users WHERE email = 'carmen.lopez@example.com'), 'Tienda Mascotas Navarra', 'retailer', 'Tienda de productos para mascotas en Pamplona', '+34948678901', 'info@tiendamascotasnavarra.es', 'Calle Mayor, 34, 31002 Pamplona, Navarra', 'Navarra', ST_GeomFromText('POINT(-1.6433 42.8167)', 4326), true),
((SELECT id FROM users WHERE email = 'david.moreno@example.com'), 'Rutas con Perros por Navarra', 'outdoor', 'Organización de rutas y actividades al aire libre con perros en Navarra', '+34948789012', 'info@rutasconperrosnavarra.es', 'Plaza del Castillo, 1, 31001 Pamplona, Navarra', 'Navarra', ST_GeomFromText('POINT(-1.6433 42.8167)', 4326), true),
((SELECT id FROM users WHERE email = 'patricia.alvarez@example.com'), 'Seguros para Mascotas Navarra', 'insurance', 'Especialistas en seguros para mascotas en Navarra', '+34948890123', 'info@segurosparamascotasnavarra.es', 'Calle de la Cadena, 18, 31001 Pamplona, Navarra', 'Navarra', ST_GeomFromText('POINT(-1.6433 42.8167)', 4326), true),
((SELECT id FROM users WHERE email = 'raul.torres@example.com'), 'Centro de Terapia Asistida con Animales de Navarra', 'therapy_center', 'Centro especializado en terapias asistadas con animales en Pamplona', '+34948901234', 'info@terapiaanimalesnavarra.es', 'Avenida Carlos VII, 45, 31007 Pamplona, Navarra', 'Navarra', ST_GeomFromText('POINT(-1.6500 42.8000)', 4326), true);