-- Additional real data for providers in País Vasco

INSERT INTO providers (owner_user_id, name, provider_type, description, phone, email, address, region, geom, verified) VALUES
((SELECT id FROM users WHERE email = 'maria.gonzalez@example.com'), 'Clínica Veterinaria Gure Albaitaritza', 'veterinary', 'Clínica veterinaria en Gorliz, País Vasco', '+34946777156', 'info@gurealbaitaritza.es', 'Andra Mari, Gorliz, Bizkaia, País Vasco', 'País Vasco', ST_GeomFromText('POINT(-2.9833 43.3833)', 4326), true),
((SELECT id FROM users WHERE email = 'carlos.ruiz@example.com'), 'Centro Veterinario Arkakuxo', 'veterinary', 'Centro veterinario en Arrigorriaga, País Vasco', '+34946712726', 'contacto@arkakuxo.es', 'Arrigorriaga, Bizkaia, País Vasco', 'País Vasco', ST_GeomFromText('POINT(-2.8833 43.2167)', 4326), true),
((SELECT id FROM users WHERE email = 'ana.sanchez@example.com'), 'AniCura Uribe Kosta', 'veterinary', 'Clínica veterinaria en Basauri con certificado "Cat Friendly"', '+34944001234', 'info@anicura.es', 'Uribe Kosta, Basauri, Bizkaia, País Vasco', 'País Vasco', ST_GeomFromText('POINT(-2.8667 43.2500)', 4326), true),
((SELECT id FROM users WHERE email = 'pablo.diaz@example.com'), 'Pastor Vasco - Centro de Adiestramiento', 'trainer', 'Especialistas en razas autóctonas como el Pastor Vasco y adiestramiento tradicional', '+34945123456', 'info@pastorvascoentrena.es', 'Carretera de Zumárraga, s/n, 20500 Arrasate, Gipuzkoa, País Vasco', 'País Vasco', ST_GeomFromText('POINT(-2.3333 43.0833)', 4326), true),
((SELECT id FROM users WHERE email = 'lucia.martinez@example.com'), 'Euskal Artzain Txakurra - Guardería Rural', 'kennel', 'Guardería especializada en razas autóctonas vascas', '+34943234567', 'reservas@euskalartzaintxakurra.es', 'Finca Mendizorrotz, 01001 Vitoria-Gasteiz, Álava, País Vasco', 'País Vasco', ST_GeomFromText('POINT(-2.6726 42.8496)', 4326), true),
((SELECT id FROM users WHERE email = 'javier.hernandez@example.com'), 'Peluquería Canina Donosti', 'grooming', 'Peluquería canina en San Sebastián con servicios personalizados', '+34943345678', 'cita@peluqueriacaninadonosti.es', 'Avenida de la Libertad, 45, 20005 San Sebastián, Gipuzkoa, País Vasco', 'País Vasco', ST_GeomFromText('POINT(-1.9750 43.3167)', 4326), true),
((SELECT id FROM users WHERE email = 'carmen.lopez@example.com'), 'Tienda Mascotas Euskal Herria', 'retailer', 'Tienda de productos para mascotas en Bilbao', '+34944456789', 'info@euskalherriamascotas.es', 'Gran Vía Don Diego López de Haro, 15, 48001 Bilbao, Bizkaia, País Vasco', 'País Vasco', ST_GeomFromText('POINT(-2.9250 43.2667)', 4326), true),
((SELECT id FROM users WHERE email = 'david.moreno@example.com'), 'Rutas con Perros por Euskadi', 'outdoor', 'Organización de rutas y actividades al aire libre con perros en el País Vasco', '+34945567890', 'info@rutasconperroseuskadi.es', 'Plaza Nueva, 1, 48005 Bilbao, Bizkaia, País Vasco', 'País Vasco', ST_GeomFromText('POINT(-2.9236 43.2640)', 4326), true),
((SELECT id FROM users WHERE email = 'patricia.alvarez@example.com'), 'Seguros para Mascotas Euskadi', 'insurance', 'Especialistas en seguros para mascotas en el País Vasco', '+34944678901', 'info@segurosparamascotaseuskadi.es', 'Calle Padre Orcolaga, 24, 48004 Bilbao, Bizkaia, País Vasco', 'País Vasco', ST_GeomFromText('POINT(-2.9333 43.2667)', 4326), true),
((SELECT id FROM users WHERE email = 'raul.torres@example.com'), 'Centro de Terapia Asistida con Animales del País Vasco', 'therapy_center', 'Centro especializado en terapias asistadas con animales en Vitoria-Gasteiz', '+34945789012', 'info@terapiaanimalespv.es', 'Calle Los Herrán, 35, 01002 Vitoria-Gasteiz, Álava, País Vasco', 'País Vasco', ST_GeomFromText('POINT(-2.6726 42.8496)', 4326), true);